### ISSUE TITLE
Error running config.sh

### ISSUE THREAD

**Issue by muzgash** [omazapa/SciDeb#1]
E: There are currently no whitespaces supported in hdd labels.

It leads to the message in the build, since no config folder is created:
W: No config/ directory; using defaults for all options

Using the default config foder that shouldnt be there in the first place.

**Comment by muzgash** [comment]
That leads to the message in the build, since no config folder is created:

W: No config/ directory; using defaults for all options

**Comment by omazapa** [comment]
The issue was fixed.
remove comment in the line 31 to set a desktop environment.

**Comment by muzgash** [comment]
Previous error was:
config.sh: line 31: config/package-lists/desktop.list.chroot: No such file or directory

And it was fixed. This is a different error that persists even wothout that line.

**Comment by omazapa** [comment]
what version of live debian are you using?
it is working for me in 5.0~
